spring.application.name=restmanager
server.port=8099

spring.datasource.url=jdbc:postgresql://localhost:5432/restrntgerencia
spring.datasource.username=admin
spring.datasource.password=b15tr0
spring.jpa.hibernate.ddl-auto=update

