spring.application.name=${API_NAME_DEFAULT:restmanager}
server.port=${API_PORT_DEFAULT:8099}

spring.datasource.url=jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME}
spring.datasource.username=${POSTGRES_DB_USER:admin}
spring.datasource.password=${POSTGRES_DB_PASSWORD:b15tr0}
spring.jpa.hibernate.ddl-auto=update

