CREATE TABLE IF NOT EXISTS usuarios (
   id BIGSERIAL PRIMARY KEY,
   nome VARCHAR(255) NOT NULL,
   cpf VARCHAR(14) NOT NULL UNIQUE,
   email VARCHAR(255) NOT NULL UNIQUE,
   login VARCHAR(100) NOT NULL UNIQUE,
   senha VARCHAR(255) NOT NULL,
   endereco VARCHAR(255),
   numero INTEGER,
   flag_proprietario BOOLEAN DEFAULT FALSE,
   data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

