INSERT INTO RESTAURANTES (ID, NOME, ENDERECO, TIPO_COZINHA, HORARIO_INICIO_FUNCTO, HORARIO_FIM_FUNCTO, ID_USUARIO) VALUES (1, 'R1', 'Addr1', 'Italiana', '12:00:00', '15:00:00', 1);
INSERT INTO RESTAURANTES (ID, NOME, ENDERECO, TIPO_COZINHA, HORARIO_INICIO_FUNCTO, HORARIO_FIM_FUNCTO, ID_USUARIO) VALUES (2, 'R2', 'Addr2', 'Brasileira', '08:00:00', '20:00:00', 2);
