CREATE TABLE RESTAURANTES (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255),
  ENDERECO VARCHAR(255),
  TIPO_COZINHA VARCHAR(100),
  HORARIO_INICIO_FUNCTO TIME,
  HORARIO_FIM_FUNCTO TIME,
  ID_USUARIO BIGINT
);
