CREATE TABLE USUARIOS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255),
  CPF VARCHAR(50),
  EMAIL VARCHAR(255),
  LOGIN VARCHAR(100),
  SENHA VARCHAR(255),
  ENDERECO VARCHAR(255),
  NUMERO INT,
  FLAG_PROPRIETARIO BOOLEAN,
  DATA_ATUALIZACAO TIMESTAMP
);
